name: Deploy Next.js to EC2 (Self-Hosted)

# Use self-hosted runner
on:
  push:
    branches:
      - main

jobs:
  deploy:
    # Tell GitHub to use your self-hosted EC2 runner
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Node.js (Node 20 for Next.js 15)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build Next.js app
      - name: Build Next.js
        run: npm run build

      # 5️⃣ Stop existing PM2 process (if running)
      - name: Stop existing PM2 process
        run: pm2 stop nextjs-app || true

      # 6️⃣ Start / Restart Next.js app using PM2
      - name: Start Next.js with PM2
        run: pm2 start npm --name "nextjs-app" -- run start -- -p 4000

      # 7️⃣ Save PM2 process list (for auto-restart on EC2 reboot)
      - name: Save PM2 process list
        run: pm2 save

      # 8️⃣ Optional: Restart Nginx (if you updated config)
      - name: Reload Nginx
        run: sudo systemctl reload nginx
