name: Deploy Next.js to EC2 (Self-Hosted)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      # 1️⃣ Checkout latest code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Cache Node.js dependencies for faster builds
      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      # 3️⃣ Setup Node.js 20 (for Next.js 15)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      # 4️⃣ Install dependencies (use cached & faster install)
      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      # 5️⃣ Build the Next.js project
      - name: Build Next.js app
        run: npm run build --max-old-space-size=1024

      # 6️⃣ Stop existing PM2 process if running
      - name: Stop existing PM2 process
        run: pm2 stop nextjs-app || true

      # 7️⃣ Start or restart Next.js app with PM2
      - name: Start Next.js with PM2
        run: pm2 start npm --name "nextjs-app" -- run start -- -p 4000

      # 8️⃣ Save PM2 process list for restart after reboot
      - name: Save PM2 process list
        run: pm2 save

      # 9️⃣ Reload Nginx to apply new configuration
      - name: Reload Nginx
        run: sudo systemctl reload nginx
